import type { Metadata } from 'next'
import { Geist, Comfortaa } from 'next/font/google'
import { ApiProvider } from '@/api/hooks'
import './globals.css'

const geistSans = Geist({
      variable: '--font-geist-sans',
      subsets: ['latin'],
})

const comfortaa = Comfortaa({
      display: 'swap',
      subsets: ['latin'],
      style: ['normal'],
      adjustFontFallback: true,
      variable: '--font-comfortaa',
      fallback: ['Arial', 'sans-serif'],
      weight: ['300', '400', '500', '600', '700'],
})

export const metadata: Metadata = {
      title: 'Create Next App',
      description: 'Generated by create next app',
}

export default function RootLayout({
      children,
}: Readonly<{
      children: React.ReactNode
}>) {
      return (
            <html
                  lang="en"
                  className={`${geistSans.variable} ${comfortaa.variable} h-full antialiased`}
            >
                  <body className="min-h-full flex flex-col">
                        <ApiProvider>{children}</ApiProvider>
                  </body>
            </html>
      )
}
